using MailKit.Net.Smtp;
using Microsoft.Extensions.Options;
using MimeKit;
using UserManagement.Api.Configuration;
using UserManagement.Api.Constants;
using UserManagement.Api.Models;

namespace UserManagement.Api.Services.EmailService.Implementation
{
    /// <summary>
    /// Handles activation email composition, link generation, and direct SMTP message transport.
    /// </summary>
    public class EmailService(
        IOptions<EmailSettings> emailOptions,
        IHttpContextAccessor httpContextAccessor,
        ILogger<EmailService> logger) : IEmailService
    {
        private readonly EmailSettings _emailSettings = emailOptions.Value;
        private readonly IHttpContextAccessor _httpContextAccessor = httpContextAccessor;
        private readonly ILogger<EmailService> _logger = logger;

        private const string DefaultBaseUrl = "http://localhost:5067";

        /// <summary>
        /// Generates an email confirmation link and dispatches the account activation email in the background.
        /// </summary>
        /// <param name="user">The user entity context.</param>
        /// <param name="token">The email confirmation token generated by Identity.</param>
        /// <returns>The generated account activation URL link.</returns>
        public Task<string> SendActivationEmailAsync(User user, string token)
        {
            // Generate link dynamically using the current request host, schema and constant route path
            HttpRequest? request = _httpContextAccessor.HttpContext?.Request;
            string baseUrl = request != null ? $"{request.Scheme}://{request.Host}" : DefaultBaseUrl;
            string confirmationLink = $"{baseUrl}/{ApiRoutes.ConfirmRegistrationPath}?email={user.Email}&token={Uri.EscapeDataString(token)}";

            _logger.LogInformation("New user registration email request. Email: {Email}, Confirmation Link: {Link}", user.Email, confirmationLink);

            // Compose HTML Email Content
            string subject = "Welcome! Confirm your registration and set your password";
            string htmlBody = $@"
                <div style='font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;'>
                    <h2 style='color: #333;'>Welcome to the System, {user.FirstName}!</h2>
                    <p>An account has been created for you. To complete your registration and set your password, please click the button below:</p>
                    <div style='text-align: center; margin: 30px 0;'>
                        <a href='{confirmationLink}' style='background-color: #007bff; color: white; padding: 12px 24px; text-decoration: none; font-weight: bold; border-radius: 5px; display: inline-block;'>Confirm Registration & Set Password</a>
                    </div>
                    <p style='color: #666; font-size: 12px;'>If the button above does not work, copy and paste this URL into your browser:</p>
                    <p style='color: #007bff; font-size: 12px; word-break: break-all;'>{confirmationLink}</p>
                </div>";

            // Send real email asynchronously in background task so API response doesn't hang
            _ = Task.Run(async () =>
            {
                try
                {
                    await SendEmailAsync(user.Email ?? string.Empty, subject, htmlBody);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Failed to send registration email to {Email}", user.Email);
                }
            });

            return Task.FromResult(confirmationLink);
        }

        /// <summary>
        /// Sends a raw email using MailKit SmtpClient over secure TLS transport.
        /// </summary>
        /// <param name="toEmail">Recipient's email address.</param>
        /// <param name="subject">Email subject line.</param>
        /// <param name="htmlMessage">HTML formatted body content.</param>
        public async Task SendEmailAsync(string toEmail, string subject, string htmlMessage)
        {
            MimeMessage message = new();
            message.From.Add(new MailboxAddress(_emailSettings.SenderName ?? "Portal", _emailSettings.SenderEmail ?? string.Empty));
            message.To.Add(new MailboxAddress("", toEmail));
            message.Subject = subject;

            BodyBuilder bodyBuilder = new() { HtmlBody = htmlMessage };
            message.Body = bodyBuilder.ToMessageBody();

            using SmtpClient client = new();
            
            // Connect to SMTP server using StartTLS on configured port
            await client.ConnectAsync(_emailSettings.SmtpServer ?? string.Empty, _emailSettings.Port, MailKit.Security.SecureSocketOptions.StartTls);
            
            // Authenticate using configured username and password
            await client.AuthenticateAsync(_emailSettings.Username ?? string.Empty, _emailSettings.Password ?? string.Empty);
            
            await client.SendAsync(message);
            await client.DisconnectAsync(true);
        }
    }
}
