using System.Threading.Tasks;
using UserManagement.Api.Models;

namespace UserManagement.Api.Services.EmailService
{
    /// <summary>
    /// Contract for dynamic HTML composition, link generation, and SMTP email dispatch services.
    /// </summary>
    public interface IEmailService
    {
        /// <summary>
        /// Generates an email confirmation link and dispatches the account activation email in the background.
        /// </summary>
        /// <param name="user">The user entity context.</param>
        /// <param name="token">The email confirmation token generated by Identity.</param>
        /// <returns>The generated account activation URL link.</returns>
        Task<string> SendActivationEmailAsync(User user, string token);

        /// <summary>
        /// Sends a raw email using configured SMTP settings.
        /// </summary>
        /// <param name="toEmail">Recipient's email address.</param>
        /// <param name="subject">Email subject line.</param>
        /// <param name="htmlMessage">HTML formatted body content.</param>
        Task SendEmailAsync(string toEmail, string subject, string htmlMessage);
    }
}
